import AmericanBurger from "./assets/images/american_burger.jpg";
import GrilledBeef from "./assets/images/grilled_beef.jpg";
import CrispyMeatball from "./assets/images/crispy_meatball.jpg";
import MeatLover from "./assets/images/meat_lover.jpg";
import Peperoni from "./assets/images/peperoni.jpg";
import BbqChicken from "./assets/images/bbq_chicken.jpg";
import Fries from "./assets/images/fires.jpg";
import Hotdog from "./assets/images/hotdog.jpg";
import Salad from "./assets/images/salad.jpg";

const pizzas = [
  {
    sku: "M-001",
    image: AmericanBurger,
    name: "American Classic Cheeseburger",
    price: 8,
    originalPrice: 10,
    toppings: [
      { sku: "M-001-T-001", name: "Bacon", price: 5 },
      { sku: "M-001-T-002", name: "Chillies", price: 3 },
      { sku: "M-001-T-003", name: "Avocado", price: 8 },
      { sku: "M-001-T-004", name: "Lettuce", price: 4 },
      { sku: "M-001-T-005", name: "Chilli", price: 2 },
      { sku: "M-001-T-006", name: "Eggs", price: 9 },
      { sku: "M-001-T-007", name: "Tomato", price: 3 },
      { sku: "M-001-T-008", name: "Pickle", price: 2 },
      { sku: "M-001-T-009", name: "Mushrooms", price: 8 },
      { sku: "M-001-T-010", name: "Mustard", price: 2 },
      { sku: "M-001-T-011", name: "Mayonnaise", price: 2 },
      { sku: "M-001-T-012", name: "BBQ Sauce", price: 2 },
      { sku: "M-001-T-013", name: "Ketchup", price: 2 },
    ],
  },
  {
    sku: "M-002",
    image: GrilledBeef,
    name: "Grilled Beef Supreme",
    price: 12,
    toppings: [
      { sku: "M-002-T-001", name: "Cilantro Lime Butter", price: 5 },
      { sku: "M-002-T-002", name: "Caramelized Cabbage with Bacon", price: 3 },
      {
        sku: "M-002-T-003",
        name: "Caramelized Onion and Blue Cheese Steak Sauce",
        price: 8,
      },
      { sku: "M-002-T-004", name: "Creamy Mushroom Sauce", price: 4 },
      {
        sku: "M-002-T-005",
        name: "Red Wine Reduction with Roasted Shallots and Bacon",
        price: 2,
      },
      { sku: "M-002-T-006", name: "Garlic Butter Sauce", price: 9 },
      { sku: "M-002-T-007", name: "Chimichurri Sauce", price: 3 },
      { sku: "M-002-T-008", name: "Easy Herbed Butter", price: 2 },
      { sku: "M-002-T-009", name: "Mustard Grilled Onions", price: 8 },
      { sku: "M-002-T-010", name: "Tomato Gravy", price: 2 },
      { sku: "M-002-T-011", name: "Sauteed Mushrooms", price: 2 },
      { sku: "M-002-T-012", name: "White Wine Mushroom Sauce", price: 2 },
      { sku: "M-002-T-013", name: "Avocado Chimichurri Sauce", price: 5 },
      { sku: "M-002-T-014", name: "Creamy Peppercorn Sauce", price: 4 },
      { sku: "M-002-T-015", name: "Bang Bang Sauce", price: 10 },
      { sku: "M-002-T-016", name: "Red Chimichurri", price: 9 },
      { sku: "M-002-T-017", name: "Yum Yum Sauce", price: 7 },
    ],
  },
  {
    sku: "M-003",
    image: CrispyMeatball,
    name: "Crispy Meatball Blast",
    price: 15,
    toppings: [
      { sku: "M-003-T-001", name: "Marinara sauce", price: 5 },
      { sku: "M-003-T-002", name: "Alfredo sauce", price: 3 },
      { sku: "M-003-T-003", name: "Pesto", price: 8 },
      { sku: "M-003-T-004", name: "BBQ sauce", price: 4 },
      { sku: "M-003-T-005", name: "Teriyaki glaze", price: 2 },
      { sku: "M-003-T-006", name: "Sweet and sour sauce", price: 9 },
      { sku: "M-003-T-007", name: "Buffalo sauce", price: 3 },
      { sku: "M-003-T-008", name: "Chimichurri", price: 2 },
      { sku: "M-003-T-009", name: "Sriracha mayo", price: 8 },
      { sku: "M-003-T-010", name: "Creamy mushroom sauce", price: 2 },
      { sku: "M-003-T-011", name: "Honey mustard", price: 2 },
      { sku: "M-003-T-012", name: "Hoisin sauce", price: 2 },
      { sku: "M-003-T-013", name: "Cranberry glaze", price: 2 },
      { sku: "M-003-T-014", name: "Chipotle aioli", price: 4 },
    ],
  },
  {
    sku: "M-004",
    image: MeatLover,
    name: "Meat Lover Pizza",
    price: 19,
    originalPrice: 24,
    toppings: [
      { sku: "M-004-T-001", name: "Pepperoni", price: 5 },
      { sku: "M-004-T-002", name: "Italian sausage", price: 3 },
      { sku: "M-004-T-003", name: "Bacon", price: 8 },
      { sku: "M-004-T-004", name: "Ham", price: 4 },
      { sku: "M-004-T-005", name: "Meatballs", price: 2 },
      { sku: "M-004-T-006", name: "Grilled chicken", price: 9 },
      { sku: "M-004-T-007", name: "Salami", price: 3 },
      { sku: "M-004-T-008", name: "Prosciutto", price: 2 },
      { sku: "M-004-T-009", name: "Chorizo", price: 8 },
      { sku: "M-004-T-010", name: "Canadian bacon", price: 2 },
      { sku: "M-004-T-011", name: "Beef (ground or sliced)", price: 2 },
      { sku: "M-004-T-012", name: "Pastrami", price: 2 },
      { sku: "M-004-T-013", name: "BBQ pulled pork", price: 2 },
      { sku: "M-004-T-014", name: "Capicola", price: 4 },
      { sku: "M-004-T-015", name: "Pancetta", price: 6 },
      { sku: "M-004-T-016", name: "Andouille sausage", price: 9 },
      { sku: "M-004-T-017", name: "Turkey sausage", price: 7 },
      { sku: "M-004-T-018", name: "Gyro meat", price: 5 },
    ],
  },
  {
    sku: "M-005",
    image: Peperoni,
    name: "Peperoni Pizza",
    price: 21,
    originalPrice: 30,
    toppings: [
      { sku: "M-005-T-001", name: "Mushrooms", price: 5 },
      { sku: "M-005-T-002", name: "Red onions", price: 3 },
      {
        sku: "M-005-T-003",
        name: "Bell peppers (green, red, yellow)",
        price: 8,
      },
      { sku: "M-005-T-004", name: "Black olives", price: 4 },
      { sku: "M-005-T-005", name: "Jalapeños", price: 2 },
      { sku: "M-005-T-006", name: "Pineapple", price: 9 },
      { sku: "M-005-T-007", name: "Fresh basil leaves", price: 3 },
      { sku: "M-005-T-008", name: "Spinach", price: 2 },
      { sku: "M-005-T-009", name: "Sun-dried tomatoes", price: 8 },
      { sku: "M-005-T-010", name: "Feta cheese", price: 2 },
      { sku: "M-005-T-011", name: "Ricotta cheese dollops", price: 2 },
      { sku: "M-005-T-012", name: "Artichoke hearts", price: 2 },
      { sku: "M-005-T-013", name: "Cherry tomatoes", price: 2 },
      { sku: "M-005-T-014", name: "Roasted garlic", price: 4 },
      { sku: "M-005-T-015", name: "Fresh mozzarella slices", price: 6 },
      { sku: "M-005-T-016", name: "Goat cheese crumbles", price: 9 },
      { sku: "M-005-T-017", name: "Caramelized onions", price: 7 },
    ],
  },
  {
    sku: "M-006",
    image: BbqChicken,
    name: "BBQ Chicken Pizza",
    price: 18,
    toppings: [
      { sku: "M-006-T-001", name: "Red onions", price: 5 },
      { sku: "M-006-T-002", name: "Pineapple", price: 3 },
      {
        sku: "M-006-T-003",
        name: "Bell peppers (green, red, yellow)",
        price: 8,
      },
      { sku: "M-006-T-004", name: "Bacon", price: 4 },
      { sku: "M-006-T-005", name: "Jalapeños", price: 2 },
      { sku: "M-006-T-006", name: "Corn", price: 9 },
      { sku: "M-006-T-007", name: "Avocado slices", price: 3 },
      { sku: "M-006-T-008", name: "Black beans", price: 2 },
      { sku: "M-006-T-009", name: "Sun-dried tomatoes", price: 8 },
      { sku: "M-006-T-010", name: "Cheddar cheese", price: 2 },
      { sku: "M-006-T-011", name: "Mozzarella cheese", price: 2 },
      { sku: "M-006-T-012", name: "Gouda cheese", price: 2 },
      { sku: "M-006-T-013", name: "Cherry tomatoes", price: 2 },
      { sku: "M-006-T-014", name: "Smoked Gouda cheese", price: 4 },
      { sku: "M-006-T-015", name: "Ranch dressing drizzle", price: 6 },
      { sku: "M-006-T-016", name: "Barbecue sauce swirl", price: 9 },
      { sku: "M-006-T-017", name: "Sliced mushrooms", price: 7 },
      { sku: "M-006-T-018", name: "Spinach", price: 4 },
      { sku: "M-006-T-019", name: "Red chili flakes", price: 2 },
    ],
  },
  {
    sku: "M-007",
    image: Fries,
    name: "French Fries",
    price: 9,
    toppings: [
      { sku: "M-007-T-001", name: "Cheddar cheese sauce", price: 5 },
      { sku: "M-007-T-002", name: "Bacon bits", price: 3 },
      { sku: "M-007-T-003", name: "Ranch dressing", price: 8 },
      { sku: "M-007-T-004", name: "Sour cream and chives", price: 4 },
      { sku: "M-007-T-005", name: "Truffle oil and parmesan cheese", price: 2 },
      { sku: "M-007-T-006", name: "Pulled pork", price: 9 },
      { sku: "M-007-T-007", name: "Chili con carne", price: 3 },
      { sku: "M-007-T-008", name: "Guacamole", price: 2 },
      {
        sku: "M-007-T-009",
        name: "Buffalo sauce and blue cheese crumbles",
        price: 8,
      },
      {
        sku: "M-007-T-010",
        name: "Poutine-style with gravy and cheese curds",
        price: 2,
      },
      { sku: "M-007-T-011", name: "BBQ pulled chicken", price: 2 },
      { sku: "M-007-T-012", name: "Kimchi and spicy mayo", price: 2 },
      { sku: "M-007-T-013", name: "Fried eggs", price: 2 },
      { sku: "M-007-T-014", name: "Salsa and melted cheese", price: 4 },
    ],
  },
  {
    sku: "M-008",
    image: Hotdog,
    name: "Classic Hotdog",
    price: 4,
    toppings: [
      { sku: "M-008-T-001", name: "Ketchup", price: 5 },
      { sku: "M-008-T-002", name: "Mustard (yellow or Dijon)", price: 3 },
      { sku: "M-008-T-003", name: "Relish (sweet or dill)", price: 8 },
      {
        sku: "M-008-T-004",
        name: "Onions (raw, grilled, or caramelized)",
        price: 4,
      },
      { sku: "M-008-T-005", name: "Crumbled potato chips", price: 2 },
      { sku: "M-008-T-006", name: "Pickles (sliced or spears)", price: 9 },
      { sku: "M-008-T-007", name: "Chopped tomatoes", price: 3 },
      { sku: "M-008-T-008", name: "Shredded lettuce", price: 2 },
      { sku: "M-008-T-009", name: "Jalapeño slices", price: 8 },
      { sku: "M-008-T-010", name: "Banana peppers", price: 2 },
      { sku: "M-008-T-011", name: "Chili con carne", price: 2 },
      { sku: "M-008-T-012", name: "Coleslaw", price: 2 },
      { sku: "M-008-T-013", name: "BBQ sauce", price: 2 },
    ],
  },
  {
    sku: "M-009",
    image: Salad,
    name: "Vegetable Salad",
    originalPrice: 39,
    price: 30,
    toppings: [
      { sku: "M-009-T-001", name: "Grilled chicken strips", price: 5 },
      { sku: "M-009-T-002", name: "Cherry tomatoes", price: 3 },
      { sku: "M-009-T-003", name: "Cucumbers (sliced or diced)", price: 8 },
      {
        sku: "M-009-T-004",
        name: "Red onion (thinly sliced or chopped)",
        price: 4,
      },
      {
        sku: "M-009-T-005",
        name: "Avocado slices",
        price: 2,
      },
      {
        sku: "M-009-T-006",
        name: "Croutons (traditional or seasoned)",
        price: 9,
      },
      { sku: "M-009-T-007", name: "Shredded carrots", price: 3 },
      { sku: "M-009-T-008", name: "Bell peppers (sliced or diced)", price: 2 },
      {
        sku: "M-009-T-009",
        name: "Hard-boiled eggs (sliced or chopped)",
        price: 8,
      },
      { sku: "M-009-T-010", name: "Feta cheese crumbles", price: 2 },
      {
        sku: "M-009-T-011",
        name: "Walnuts or pecans (toasted or candied)",
        price: 2,
      },
      { sku: "M-009-T-012", name: "Dried cranberries or raisins", price: 2 },
      { sku: "M-009-T-013", name: "Sliced almonds", price: 2 },
    ],
  },
];

export default pizzas;
